import { BuffRarity, PassiveBuff } from '../types';

export const PASSIVE_BUFFS: Record<string, PassiveBuff> = {
  carlsson_mode: {
    id: 'carlsson_mode',
    name: 'Carlsson Protocol',
    description: 'A legendary overcharge. All shots home in, speed increases and damage is brutal.',
    stackSummary: 'Ultimate Power',
    rarity: BuffRarity.EXCLUSIVE,
    exclusive: true,
    icon: 'Trophy',
    tags: ['carlsson', 'damage', 'utility'],
    maxStacks: 1,
  },
  dmg_up: {
    id: 'dmg_up',
    name: 'Kinetic Overcharge',
    description: 'Base damage +25% per stack',
    stackSummary: '+25% damage',
    rarity: BuffRarity.COMMON,
    icon: 'Zap',
    tags: ['damage'],
    maxStacks: 8,
  },
  crit_up: {
    id: 'crit_up',
    name: 'Precision Optics',
    description: 'Crit chance +12% per stack',
    stackSummary: '+12% crit',
    rarity: BuffRarity.COMMON,
    icon: 'Target',
    tags: ['damage'],
    maxStacks: 6,
  },
  health_up: {
    id: 'health_up',
    name: 'Composite Hull',
    description: '+60 max HP and heals 80 on pick',
    stackSummary: '+60 HP',
    rarity: BuffRarity.COMMON,
    icon: 'Shield',
    tags: ['defense'],
    maxStacks: 5,
  },
  speed_up: {
    id: 'speed_up',
    name: 'Afterburner',
    description: 'Move speed +18% per stack',
    stackSummary: '+18% speed',
    rarity: BuffRarity.COMMON,
    icon: 'Flame',
    tags: ['mobility'],
    maxStacks: 5,
  },
  energy_up: {
    id: 'energy_up',
    name: 'Flux Capacitor',
    description: '+40 max energy and refill dash on pick',
    stackSummary: '+40 energy',
    rarity: BuffRarity.COMMON,
    icon: 'Zap',
    tags: ['mobility'],
    maxStacks: 4,
  },
  magnet_up: {
    id: 'magnet_up',
    name: 'Singularity Field',
    description: 'Huge pickup magnet for 12s',
    stackSummary: 'Magnet aura',
    rarity: BuffRarity.RARE,
    icon: 'Magnet',
    tags: ['economy'],
    maxStacks: 3,
  },
  regen_up: {
    id: 'regen_up',
    name: 'Nano-Bot Swarm',
    description: 'Regenerate 4 HP/s per stack',
    stackSummary: '+4 HP/s',
    rarity: BuffRarity.RARE,
    icon: 'Activity',
    tags: ['defense'],
    maxStacks: 5,
  },
  bounce_up: {
    id: 'bounce_up',
    name: 'Kinetic Rebound',
    description: 'Projectiles bounce off walls +1 per stack',
    stackSummary: '+1 bounce',
    rarity: BuffRarity.RARE,
    icon: 'RotateCcw',
    tags: ['projectile'],
    maxStacks: 4,
  },
  lifesteal_up: {
    id: 'lifesteal_up',
    name: 'Soul Siphon',
    description: 'Heal 8% of enemy max HP on kill per stack',
    stackSummary: '+8% lifesteal',
    rarity: BuffRarity.EPIC,
    icon: 'HeartPulse',
    tags: ['defense', 'damage'],
    maxStacks: 4,
  },
  shield_up: {
    id: 'shield_up',
    name: 'Second Wind',
    description: 'Grants 1 extra life — when you would die, survive at 30% hull once',
    stackSummary: '+1 extra life',
    rarity: BuffRarity.EPIC,
    icon: 'ShieldCheck',
    tags: ['defense'],
    maxStacks: 2,
  },
  explosive: {
    id: 'explosive',
    name: 'Volatile Rounds',
    description: '+15% chance for AoE explosions per stack',
    stackSummary: '+15% explode',
    rarity: BuffRarity.EPIC,
    icon: 'Bomb',
    tags: ['damage', 'fire'],
    maxStacks: 4,
  },
  multishot_up: {
    id: 'multishot_up',
    name: 'Split-Fire Array',
    description: '+1 projectile per stack, but -8% fire rate per stack',
    stackSummary: '+1 shot / -8% ROF',
    rarity: BuffRarity.EPIC,
    icon: 'Swords',
    tags: ['projectile'],
    maxStacks: 4,
    wowFactor: 2,
  },
  overdrive_p: {
    id: 'overdrive_p',
    name: 'Overdrive',
    description: '+50% fire rate permanently, but -15% damage per shot',
    stackSummary: '+50% ROF / -15% dmg',
    rarity: BuffRarity.EPIC,
    icon: 'Zap',
    tags: ['damage'],
    maxStacks: 1,
  },
  time_slow_p: {
    id: 'time_slow_p',
    name: 'Chrono Disruption',
    description: 'Enemies move 70% slower permanently, but you move 15% slower too',
    stackSummary: '70% enemy slow / -15% speed',
    rarity: BuffRarity.EPIC,
    icon: 'RotateCcw',
    tags: ['control'],
    maxStacks: 1,
  },
  orbital: {
    id: 'orbital',
    name: 'Sentinel Drone',
    description: '+1 orbiting damage drone',
    stackSummary: '+1 drone',
    rarity: BuffRarity.LEGENDARY,
    icon: 'CircleIcon',
    tags: ['damage'],
    maxStacks: 3,
  },
  lighting: {
    id: 'lighting',
    name: 'Arc Discharger',
    description: 'Shots chain lightning to nearby foes',
    stackSummary: 'Chain lightning',
    rarity: BuffRarity.LEGENDARY,
    icon: 'Zap',
    tags: ['damage', 'lightning'],
    maxStacks: 1,
  },
  pierce_up: {
    id: 'pierce_up',
    name: 'Plasma Shredders',
    description: 'Permanent piercing shots',
    stackSummary: 'Permanent pierce',
    rarity: BuffRarity.LEGENDARY,
    icon: 'MoveRight',
    tags: ['projectile'],
    maxStacks: 1,
  },
  gravity_well: {
    id: 'gravity_well',
    name: 'Event Horizon',
    description: 'Hits pull enemies toward impact',
    stackSummary: 'Gravity pulls',
    rarity: BuffRarity.LEGENDARY,
    icon: 'Zap',
    tags: ['control'],
    maxStacks: 1,
  },
  backshot: {
    id: 'backshot',
    name: 'Rear Ambush',
    description: 'Also fire a backward shot each burst',
    stackSummary: 'Rear shot',
    rarity: BuffRarity.RARE,
    icon: 'MoveRight',
    tags: ['projectile'],
    maxStacks: 1,
  },
  spiral_shot: {
    id: 'spiral_shot',
    name: 'Helix Rounds',
    description: 'Projectiles drift in a spiral path',
    stackSummary: 'Spiral path',
    rarity: BuffRarity.RARE,
    icon: 'RotateCcw',
    tags: ['projectile'],
    maxStacks: 1,
  },
  burn_dot: {
    id: 'burn_dot',
    name: 'Incendiary Coating',
    description: 'Crits leave burning DoT on enemies',
    stackSummary: 'Burn on crit',
    rarity: BuffRarity.EPIC,
    icon: 'Flame',
    tags: ['fire', 'damage'],
    maxStacks: 2,
  },
  frost_slow: {
    id: 'frost_slow',
    name: 'Cryo Payload',
    description: 'Hits briefly chill enemy movement',
    stackSummary: 'Chill hits',
    rarity: BuffRarity.RARE,
    icon: 'Target',
    tags: ['control', 'frost'],
    maxStacks: 3,
  },
  thorns: {
    id: 'thorns',
    name: 'Retribution Plating',
    description: 'Contact damage reflects to attackers',
    stackSummary: 'Thorns',
    rarity: BuffRarity.EPIC,
    icon: 'Shield',
    tags: ['defense'],
    maxStacks: 2,
  },
  dash_iframes: {
    id: 'dash_iframes',
    name: 'Phase Slip',
    description: 'Dash grants brief invulnerability',
    stackSummary: 'Dash i-frames',
    rarity: BuffRarity.EPIC,
    icon: 'Zap',
    tags: ['mobility', 'defense'],
    maxStacks: 1,
  },
  combo_boost: {
    id: 'combo_boost',
    name: 'Kill Streak',
    description: 'Combo multiplier +25% per stack',
    stackSummary: '+25% combo',
    rarity: BuffRarity.RARE,
    icon: 'Trophy',
    tags: ['economy'],
    maxStacks: 4,
  },
  score_burst: {
    id: 'score_burst',
    name: 'Bounty Hunter',
    description: 'Score pickups worth 2x for 10s',
    stackSummary: '2x score drops',
    rarity: BuffRarity.COMMON,
    icon: 'Trophy',
    tags: ['economy'],
    maxStacks: 3,
  },
  emergency_shield: {
    id: 'emergency_shield',
    name: 'Emergency Pod',
    description: 'Grants 1 extra life if you have none (once per run)',
    stackSummary: '+1 extra life',
    rarity: BuffRarity.LEGENDARY,
    icon: 'ShieldCheck',
    tags: ['defense'],
    maxStacks: 1,
  },
  ricochet_plus: {
    id: 'ricochet_plus',
    name: 'Ricochet Matrix',
    description: 'Ricochets seek a new target',
    stackSummary: 'Smart ricochet',
    rarity: BuffRarity.LEGENDARY,
    icon: 'RotateCcw',
    tags: ['projectile'],
    maxStacks: 1,
  },
  vampiric_burst: {
    id: 'vampiric_burst',
    name: 'Blood Nova',
    description: 'Every 20 kills: heal 25% max HP',
    stackSummary: 'Kill heal burst',
    rarity: BuffRarity.EPIC,
    icon: 'HeartPulse',
    tags: ['defense'],
    maxStacks: 2,
  },
  chain_crit: {
    id: 'chain_crit',
    name: 'Cascading Focus',
    description: 'Crits increase next shot crit chance',
    stackSummary: 'Crit snowball',
    rarity: BuffRarity.RARE,
    icon: 'Target',
    tags: ['damage'],
    maxStacks: 3,
  },
  wide_arc: {
    id: 'wide_arc',
    name: 'Scatter Cone',
    description: 'Wider spread, +1 projectile',
    stackSummary: 'Wide spread',
    rarity: BuffRarity.COMMON,
    icon: 'Swords',
    tags: ['projectile'],
    maxStacks: 3,
  },
  overcharge_dash: {
    id: 'overcharge_dash',
    name: 'Blink Strike',
    description: 'Dash costs 20 less energy',
    stackSummary: 'Cheaper dash',
    rarity: BuffRarity.COMMON,
    icon: 'Zap',
    tags: ['mobility'],
    maxStacks: 3,
  },
  volatile_death: {
    id: 'volatile_death',
    name: 'Death Blossom',
    description: 'Enemies explode on death (small AoE)',
    stackSummary: 'Death explosions',
    rarity: BuffRarity.RARE,
    icon: 'Bomb',
    tags: ['fire', 'damage'],
    maxStacks: 2,
  },
  time_dilation: {
    id: 'time_dilation',
    name: 'Temporal Bubble',
    description: '6s slow-mo field every 40s',
    stackSummary: 'Timed slow field',
    rarity: BuffRarity.LEGENDARY,
    icon: 'RotateCcw',
    tags: ['control'],
    maxStacks: 1,
  },
  hunter_mark: {
    id: 'hunter_mark',
    name: 'Marked Prey',
    description: '+20% damage vs enemies below 50% HP',
    stackSummary: 'Execute damage',
    rarity: BuffRarity.RARE,
    icon: 'Target',
    tags: ['damage'],
    maxStacks: 3,
  },
  multishot_apocalypse: {
    id: 'multishot_apocalypse',
    name: 'Multishot Apocalypse',
    description: '+5 projectiles in a wide cone. The swarm obeys.',
    stackSummary: '+5 shots — YES',
    rarity: BuffRarity.EXCLUSIVE,
    icon: 'Swords',
    tags: ['projectile', 'damage'],
    maxStacks: 2,
    exclusive: true,
    wowFactor: 3,
    threatWeight: 12,
  },
  bullet_storm: {
    id: 'bullet_storm',
    name: 'Bullet Storm',
    description: 'Fire rate x1.8. Damage -10%. Unrelenting pressure.',
    stackSummary: 'x1.8 fire rate',
    rarity: BuffRarity.EXCLUSIVE,
    icon: 'Flame',
    tags: ['damage'],
    maxStacks: 1,
    exclusive: true,
    wowFactor: 3,
    threatWeight: 10,
  },
  infinity_pierce: {
    id: 'infinity_pierce',
    name: 'Infinity Pierce',
    description: 'All shots pierce every target. +1 wall bounce.',
    stackSummary: 'Pierce ALL',
    rarity: BuffRarity.EXCLUSIVE,
    icon: 'MoveRight',
    tags: ['projectile'],
    maxStacks: 1,
    exclusive: true,
    wowFactor: 3,
    threatWeight: 9,
  },
  orbital_legion: {
    id: 'orbital_legion',
    name: 'Orbital Legion',
    description: 'Deploy 3 sentinel drones instantly.',
    stackSummary: '+3 drones NOW',
    rarity: BuffRarity.EXCLUSIVE,
    icon: 'CircleIcon',
    tags: ['damage'],
    maxStacks: 1,
    exclusive: true,
    wowFactor: 3,
    threatWeight: 10,
  },
  chain_god: {
    id: 'chain_god',
    name: 'Chain God',
    description: 'Lightning chains to 2 extra targets per hit.',
    stackSummary: 'Chain x2',
    rarity: BuffRarity.EXCLUSIVE,
    icon: 'Zap',
    tags: ['damage', 'lightning'],
    maxStacks: 1,
    exclusive: true,
    wowFactor: 3,
    threatWeight: 9,
  },
  glass_cannon_omega: {
    id: 'glass_cannon_omega',
    name: 'Glass Cannon Omega',
    description: '+80% damage. -25% max HP. Pure aggression.',
    stackSummary: '+80% dmg / -25% HP',
    rarity: BuffRarity.EXCLUSIVE,
    icon: 'Zap',
    tags: ['damage'],
    maxStacks: 1,
    exclusive: true,
    wowFactor: 2,
    threatWeight: 8,
  },
  kill_satellite: {
    id: 'kill_satellite',
    name: 'Kill Satellite',
    description: 'Every 8 kills: pulse damage across the sector.',
    stackSummary: 'Kill pulse',
    rarity: BuffRarity.EXCLUSIVE,
    icon: 'Bomb',
    tags: ['damage'],
    maxStacks: 1,
    exclusive: true,
    wowFactor: 2,
    threatWeight: 7,
  },
  void_rift: {
    id: 'void_rift',
    name: 'Void Rift',
    description: 'Every 12s: gravitational pull damages nearby foes.',
    stackSummary: 'Void pulse',
    rarity: BuffRarity.EXCLUSIVE,
    icon: 'RotateCcw',
    tags: ['control'],
    maxStacks: 1,
    exclusive: true,
    wowFactor: 2,
    threatWeight: 7,
  },
  cursed_ammo: {
    id: 'cursed_ammo',
    name: 'Cursed Ammo',
    description: 'Damage -30%, but fires 6 extra chaotic bouncing explosive shots per trigger!',
    stackSummary: 'Tradeoff: CHAOS',
    rarity: BuffRarity.EXCLUSIVE,
    icon: 'Sparkles',
    tags: ['damage'],
    maxStacks: 1,
    exclusive: true,
    wowFactor: 3,
    threatWeight: 10,
  },
  neon_blood: {
    id: 'neon_blood',
    name: 'Neon Blood',
    description: 'Max Health +200, taking damage spawns furious homing missiles.',
    stackSummary: 'Counter-attack',
    rarity: BuffRarity.LEGENDARY,
    icon: 'Shield',
    tags: ['defense', 'damage'],
    maxStacks: 3,
    wowFactor: 1,
    threatWeight: 5,
  },
  chrono_glitch: {
    id: 'chrono_glitch',
    name: 'Chrono Glitch',
    description: 'When hit, completely freeze time for 3 seconds and gain massive speed.',
    stackSummary: 'Time stop on hit',
    rarity: BuffRarity.LEGENDARY,
    icon: 'Zap',
    tags: ['defense', 'utility'],
    maxStacks: 2,
    wowFactor: 2,
    threatWeight: 6,
  },
  boss_slayer: {
    id: 'boss_slayer',
    name: 'Boss Slayer',
    description: '+35% damage vs bosses and elites.',
    stackSummary: '+35% boss dmg',
    rarity: BuffRarity.RARE,
    icon: 'Swords',
    tags: ['boss', 'damage'],
    maxStacks: 3,
    threatWeight: 4,
  },
  arena_stabilizer: {
    id: 'arena_stabilizer',
    name: 'Arena Stabilizer',
    description: '+80 max HP and 5 HP/s regen while a boss is active.',
    stackSummary: 'Boss tank',
    rarity: BuffRarity.RARE,
    icon: 'Shield',
    tags: ['boss', 'defense'],
    maxStacks: 2,
    threatWeight: 3,
  },
  salvage_radar: {
    id: 'salvage_radar',
    name: 'Salvage Radar',
    description: 'Boss kills grant +25 bonus scrap.',
    stackSummary: '+25 boss scrap',
    rarity: BuffRarity.EPIC,
    icon: 'Target',
    tags: ['boss', 'economy'],
    maxStacks: 2,
    threatWeight: 2,
  },
  tyrant_fury: {
    id: 'tyrant_fury',
    name: 'Tyrant Fury',
    description: 'Ultimate charge fills 20% faster during boss fights.',
    stackSummary: 'Boss ult',
    rarity: BuffRarity.EPIC,
    icon: 'Zap',
    tags: ['boss', 'utility'],
    maxStacks: 2,
    threatWeight: 4,
  },
  hive_bulwark: {
    id: 'hive_bulwark',
    name: 'Hive Bulwark',
    description: 'Dash costs 30% less energy during boss arenas.',
    stackSummary: 'Boss dash',
    rarity: BuffRarity.RARE,
    icon: 'Flame',
    tags: ['boss', 'mobility'],
    maxStacks: 2,
    threatWeight: 3,
  },
  void_hunter: {
    id: 'void_hunter',
    name: 'Void Hunter',
    description: 'Crit chance +18% while bossActive.',
    stackSummary: 'Boss crit',
    rarity: BuffRarity.LEGENDARY,
    icon: 'Target',
    tags: ['boss', 'damage'],
    maxStacks: 2,
    threatWeight: 5,
  },
  regent_protocol: {
    id: 'regent_protocol',
    name: 'Regent Protocol',
    description: 'After boss kill: heal 25% max HP and +15 scrap.',
    stackSummary: 'Post-boss heal',
    rarity: BuffRarity.LEGENDARY,
    icon: 'HeartPulse',
    tags: ['boss', 'defense', 'economy'],
    maxStacks: 1,
    threatWeight: 4,
  },
  crimson_overdrive: {
    id: 'crimson_overdrive',
    name: 'Crimson Overdrive',
    description: 'Entering a boss arena grants 8s overdrive.',
    stackSummary: 'Arena burst',
    rarity: BuffRarity.EPIC,
    icon: 'Activity',
    tags: ['boss', 'damage'],
    maxStacks: 1,
    threatWeight: 5,
  },

  // Mystery buffs — revealed only on pick (good or bad)
  mys_dmg_burst: {
    id: 'mys_dmg_burst',
    name: '???',
    description: 'Unknown signal. Contents classified.',
    stackSummary: 'Mystery',
    rarity: BuffRarity.MYSTERY,
    icon: 'Zap',
    tags: ['mystery'],
    maxStacks: 3,
  },
  mys_hp_drain: {
    id: 'mys_hp_drain',
    name: '???',
    description: 'Unknown signal. Contents classified.',
    stackSummary: 'Mystery',
    rarity: BuffRarity.MYSTERY,
    icon: 'Activity',
    tags: ['mystery'],
    maxStacks: 3,
  },
  mys_speed_curse: {
    id: 'mys_speed_curse',
    name: '???',
    description: 'Unknown signal. Contents classified.',
    stackSummary: 'Mystery',
    rarity: BuffRarity.MYSTERY,
    icon: 'MoveRight',
    tags: ['mystery'],
    maxStacks: 3,
  },
  mys_shield_gift: {
    id: 'mys_shield_gift',
    name: '???',
    description: 'Unknown signal. Contents classified.',
    stackSummary: 'Mystery',
    rarity: BuffRarity.MYSTERY,
    icon: 'ShieldCheck',
    tags: ['mystery'],
    maxStacks: 3,
  },
  mys_scrap_tax: {
    id: 'mys_scrap_tax',
    name: '???',
    description: 'Unknown signal. Contents classified.',
    stackSummary: 'Mystery',
    rarity: BuffRarity.MYSTERY,
    icon: 'Bomb',
    tags: ['mystery'],
    maxStacks: 3,
  },
  mys_multishot: {
    id: 'mys_multishot',
    name: '???',
    description: 'Unknown signal. Contents classified.',
    stackSummary: 'Mystery',
    rarity: BuffRarity.MYSTERY,
    icon: 'Target',
    tags: ['mystery'],
    maxStacks: 3,
  },
};
