import type React from 'react';
import type { IconProps } from './IconProps';
import type { IconName } from './types';
import { ShipTankIcon, ShipFastIcon, ShipBalancedIcon } from './glyphs/ships';
import {
  CompanionGuardianIcon,
  CompanionScoutIcon,
  CompanionHealerIcon,
  CompanionGunnerIcon,
} from './glyphs/companions';
import {
  SlotCannonAIcon,
  SlotCannonBIcon,
  SlotUltimateIcon,
  SlotArmorIcon,
  SlotMobilityIcon,
} from './glyphs/slots';
import {
  BuffZapIcon,
  BuffTargetIcon,
  BuffShieldIcon,
  BuffFlameIcon,
  BuffMagnetIcon,
  BuffActivityIcon,
  BuffRotateIcon,
  BuffHeartIcon,
  BuffShieldCheckIcon,
  BuffBombIcon,
  BuffSwordsIcon,
  BuffCircleIcon,
  BuffMoveRightIcon,
  BuffTrophyIcon,
  BuffSparklesIcon,
  ShopGaugeIcon,
  ShopPackageIcon,
  ShopTrendingIcon,
  ShopWindIcon,
  ShopCloudIcon,
  ShopArrowUpIcon,
  ShopBotIcon,
} from './glyphs/buffs';
import {
  RailsTunnelIcon,
  RailsAsteroidIcon,
  RailsVoidIcon,
  RailsShieldIcon,
  RailsGunIcon,
  RailsClockIcon,
  RailsHeartIcon,
  RailsStarIcon,
  RailsBoltIcon,
  RailsBombIcon,
  MinibossWaveIcon,
  MinibossSpeedIcon,
  MinibossStrikeIcon,
  MinibossGhostIcon,
  MinibossDrainIcon,
  MinibossApexIcon,
  MinibossTimeIcon,
} from './glyphs/rails';
import {
  UiMenuIcon,
  UiLockIcon,
  UiRelicIcon,
  UiArtifactIcon,
  UiDashIcon,
  UiUltimateIcon,
  UiPlayIcon,
  UiSparklesIcon,
  UiTrophyIcon,
  UiMapIcon,
  UiWrenchIcon,
  UiGemIcon,
  UiActivityIcon,
  UiAlertIcon,
  UiFallbackIcon,
  UiShieldIcon,
} from './glyphs/ui';

export type IconComponent = React.FC<IconProps>;

export const ICON_REGISTRY: Record<IconName, IconComponent> = {
  'ship.tank': ShipTankIcon,
  'ship.fast': ShipFastIcon,
  'ship.balanced': ShipBalancedIcon,
  'companion.guardian': CompanionGuardianIcon,
  'companion.scout': CompanionScoutIcon,
  'companion.healer': CompanionHealerIcon,
  'companion.gunner': CompanionGunnerIcon,
  'slot.cannonA': SlotCannonAIcon,
  'slot.cannonB': SlotCannonBIcon,
  'slot.ultimate': SlotUltimateIcon,
  'slot.armor': SlotArmorIcon,
  'slot.mobility': SlotMobilityIcon,
  'buff.zap': BuffZapIcon,
  'buff.target': BuffTargetIcon,
  'buff.shield': BuffShieldIcon,
  'buff.flame': BuffFlameIcon,
  'buff.magnet': BuffMagnetIcon,
  'buff.activity': BuffActivityIcon,
  'buff.rotate': BuffRotateIcon,
  'buff.heart': BuffHeartIcon,
  'buff.shieldCheck': BuffShieldCheckIcon,
  'buff.bomb': BuffBombIcon,
  'buff.swords': BuffSwordsIcon,
  'buff.circle': BuffCircleIcon,
  'buff.moveRight': BuffMoveRightIcon,
  'buff.trophy': BuffTrophyIcon,
  'buff.sparkles': BuffSparklesIcon,
  'shop.gauge': ShopGaugeIcon,
  'shop.package': ShopPackageIcon,
  'shop.trending': ShopTrendingIcon,
  'shop.wind': ShopWindIcon,
  'shop.cloud': ShopCloudIcon,
  'shop.arrowUp': ShopArrowUpIcon,
  'shop.bot': ShopBotIcon,
  'rails.tunnel': RailsTunnelIcon,
  'rails.asteroid': RailsAsteroidIcon,
  'rails.void': RailsVoidIcon,
  'rails.shield': RailsShieldIcon,
  'rails.gun': RailsGunIcon,
  'rails.clock': RailsClockIcon,
  'rails.heart': RailsHeartIcon,
  'rails.star': RailsStarIcon,
  'rails.bolt': RailsBoltIcon,
  'rails.bomb': RailsBombIcon,
  'miniboss.shield': RailsShieldIcon,
  'miniboss.wave': MinibossWaveIcon,
  'miniboss.speed': MinibossSpeedIcon,
  'miniboss.strike': MinibossStrikeIcon,
  'miniboss.ghost': MinibossGhostIcon,
  'miniboss.drain': MinibossDrainIcon,
  'miniboss.apex': MinibossApexIcon,
  'miniboss.time': MinibossTimeIcon,
  'ui.menu': UiMenuIcon,
  'ui.lock': UiLockIcon,
  'ui.relic': UiRelicIcon,
  'ui.artifact': UiArtifactIcon,
  'ui.dash': UiDashIcon,
  'ui.ultimate': UiUltimateIcon,
  'ui.play': UiPlayIcon,
  'ui.sparkles': UiSparklesIcon,
  'ui.trophy': UiTrophyIcon,
  'ui.map': UiMapIcon,
  'ui.wrench': UiWrenchIcon,
  'ui.gem': UiGemIcon,
  'ui.activity': UiActivityIcon,
  'ui.alert': UiAlertIcon,
  'ui.fallback': UiFallbackIcon,
};
